/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        "on-primary-fixed": "#00164e",
        "on-surface-variant": "#444651",
        "primary-container": "#1e3a8a",
        "surface-variant": "#dae2fd",
        "surface-container-highest": "#dae2fd",
        "surface-dim": "#d2d9f4",
        "on-secondary-fixed": "#390c00",
        "surface": "#faf8ff",
        "on-tertiary": "#ffffff",
        "on-secondary": "#ffffff",
        "surface-tint": "#4059aa",
        "surface-container-lowest": "#ffffff",
        "on-secondary-container": "#5d1900",
        "on-primary-fixed-variant": "#264191",
        "outline": "#757682",
        "tertiary-fixed-dim": "#79db8d",
        "tertiary-container": "#004b1f",
        "on-primary-container": "#90a8ff",
        "primary-fixed-dim": "#b6c4ff",
        "surface-bright": "#faf8ff",
        "inverse-surface": "#283044",
        "on-surface": "#131b2e",
        "on-error-container": "#93000a",
        "on-background": "#131b2e",
        "on-tertiary-fixed": "#00210a",
        "inverse-on-surface": "#eef0ff",
        "tertiary-fixed": "#95f8a7",
        "surface-container": "#eaedff",
        "surface-container-high": "#e2e7ff",
        "on-error": "#ffffff",
        "tertiary": "#003212",
        "background": "#faf8ff",
        "secondary-fixed": "#ffdbd0",
        "outline-variant": "#c5c5d3",
        "secondary-fixed-dim": "#ffb59d",
        "on-tertiary-fixed-variant": "#005323",
        "surface-container-low": "#f2f3ff",
        "on-secondary-fixed-variant": "#832600",
        "inverse-primary": "#b6c4ff",
        "error": "#ba1a1a",
        "primary": "#00236f",
        "error-container": "#ffdad6",
        "on-primary": "#ffffff",
        "secondary-container": "#fe6a34",
        "secondary": "#ab3500",
        "on-tertiary-container": "#5ec074",
        "primary-fixed": "#dce1ff",
        "obsidian": "#0b0d19",
        "obsidian-card": "#13172b",
        "neon-saffron": "#fe6a34",
        "neon-violet": "#7c3aed"
      },
      fontFamily: {
        headline: ["Outfit", "sans-serif"],
        body: ["Inter", "sans-serif"]
      },
      boxShadow: {
        'glow-primary': '0 0 25px -5px rgba(64, 89, 170, 0.4)',
        'glow-saffron': '0 0 25px -5px rgba(254, 106, 52, 0.4)',
        'glow-violet': '0 0 25px -5px rgba(124, 58, 237, 0.4)',
        'glass': '0 8px 32px 0 rgba(0, 0, 0, 0.2)'
      }
    },
  },
  plugins: [],
}
